export const SUITE_APPS = [
  ['NinjaWord', '/word'],
  ['NinjaCalc', '/excel'],
  ['NinjaSlides', '/powerpoint'],
  ['Blueline', 'blueline'],
  ['NinjaBoard', '/board'],
  ['NinjaTime', '/time'],
  ['NinjaNotes', '/notes'],
  ['NinjaPDF', '/pdf'],
  ['NinjaImage', '/image'],
  ['NinjaSVG', '/svg'],
  ['NinjaMeet', '/meet'],
  ['NinjaChat', '/chat'],
  ['NinjaDrop', '/drop'],
  ['NinjaSync', '/sync'],
] as const;
